// Interface that enforces data integrity for any Articles being listed on the site.
export interface Article {
Name: string,
NewsArticle: string,
PublishDate: Date,
Description: string,
Ratings: {
  userId: string;
  value: number;
}[],
Category: string,
Views: number
}

// Example data that will be used for demonstrating the Recent page functionality.
export const listOfArticles: Article[] = [
  {Name: "TypeScript Date Tutorials", 
    NewsArticle: "https://pythonguides.com/typescript-date/", 
    PublishDate: new Date(2026, 0, 27), 
    Description: "This article is a comprehensive tutorial explaining how to create, format, and manipulate dates using TypeScript's native Date object. It covers practical topics like time zones, custom formatting, and performing common operations, and also suggests libraries like date-fns for complex tasks.", 
    Ratings: [{ userId: "u1", value: 2 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 4 },
  { userId: "u4", value: 5 }],
    Category: "Programming",
    Views: 37},
  {Name: "I Switched From Windows 11 to Linux Mint. Here Are 7 Things It Does Way Better", 
    NewsArticle: "https://www.pcmag.com/opinions/i-switched-from-windows-11-to-linux-mint-7-things-it-does-way-better?test_uuid=04IpBmWGZleS0I0J3epvMrC&test_variant=B", 
    PublishDate: new Date(2026, 0, 28), 
    Description: "This article details a user's experience switching from Windows 11 to Linux Mint, highlighting seven key areas where Mint excels. It also frankly addresses the trade-offs, including a lack of mainstream software like Adobe Creative Cloud and Microsoft Office.", 
    Ratings: [
  { userId: "u2", value: 4 },
  { userId: "u3", value: 4 },
  { userId: "u4", value: 5 }],
    Category: "Operating System",
    Views: 26},
  {Name: "Nationwide is deepening its use of cloud services with AWS", 
    NewsArticle: "https://www.cloudcomputing-news.net/news/nationwide-is-deepening-its-use-of-cloud-services-with-aws/", 
    PublishDate: new Date(2026, 0, 24), 
    Description: "Nationwide Building Society, a large UK financial institution, is expanding its existing cloud partnership with AWS. This move is part of a gradual, long-term strategy to consolidate more of its operational workloads on AWS to achieve greater flexibility, resilience, and improved customer and employee experiences.", 
    Ratings: [{ userId: "u1", value: 2 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 4 },
  { userId: "u4", value: 5 }],
    Category: "Cloud Computing",
    Views: 73},
  {Name: "CS846: The Role of LLMs in Software Engineering (Week 4)", 
    NewsArticle: "https://cs.uwaterloo.ca/~m2nagapp/courses/CS846/1261/schedule.html", 
    PublishDate: new Date(2026, 0, 27), 
    Description: "This university course schedule for Week 4 focuses on 'Requirements Engineering using Generative AI.' It lists several academic papers that investigate how LLMs like ChatGPT can be used for requirements elicitation, specification generation, and prompt engineering, highlighting the growing academic interest in AI-assisted software development.",
    Ratings: [{ userId: "u1", value: 1 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 4 },
  { userId: "u4", value: 5 }],
    Category: "Computer Science Education",
    Views: 42},
  {Name: "QNX vs Zephyr vs Embedded Linux in 2026: How Safety-Critical Teams Actually Choose", 
    NewsArticle: "https://promwad.com/news/qnx-zephyr-embedded-linux-safety-critical-2026", 
    PublishDate: new Date(2026, 0, 26), 
    Description: "This in-depth industry analysis explores how engineering teams select operating systems for safety-critical projects in 2026. It moves beyond simple feature comparisons to discuss certification risk, long-term support, and the rise of hybrid architectures, comparing the strengths of QNX's predictability, Zephyr's openness, and Embedded Linux's flexibility.",
    Ratings: [{ userId: "u1", value: 5 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 4 },
  { userId: "u4", value: 1 }],
    Category: "Operating System",
    Views: 58},
  {Name: "AI Boom Drives Data Center Capex to $1.7 Trillion by 2030", 
    NewsArticle: "https://www.prnewswire.com/news-releases/ai-boom-drives-data-center-capex-to-1-7-trillion-by-2030--according-to-delloro-group-302681759.html", 
    PublishDate: new Date(2026, 1, 10), 
    Description: "A report from Dell'Oro Group projects that the artificial intelligence boom will fuel a massive surge in data center capital expenditures, reaching $1.7 trillion by 2030. The report highlights that the top four US hyperscalers are expected to represent about half of this global spending as they deploy larger and more complex AI clusters.",
    Ratings: [{ userId: "u1", value: 5 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 2 },
  { userId: "u4", value: 5 }],
    Category: "Cloud Computing",
    Views: 95},
  {Name: "The Only Programming Languages Worth Learning in 2026", 
    NewsArticle: "https://content.techgig.com/career-advice/only-programming-languages-worth-learning-2026/articleshow/126939089.cms", 
    PublishDate: new Date(2026, 0, 20), 
    Description: "This career guide for tech students argues that depth in a key language beats breadth. It recommends TypeScript for modern apps (noting it now surpasses JavaScript and Python in GitHub contributors), Python for AI orchestration, Go for infrastructure, Rust for secure systems, and Java/C# for enterprise stability, emphasizing long-term relevance over trends.",
    Ratings: [{ userId: "u1", value: 5 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 4 },
  { userId: "u4", value: 5 }],
    Category: "Programming",
    Views: 81},
  {Name: "The 6 Linux distros I expect to rule 2026", 
    NewsArticle: "https://www.zdnet.com/article/linux-2026-best-distros/", 
    PublishDate: new Date(2026, 1, 8), 
    Description: "A ZDNET columnist predicts which Linux distributions will dominate in 2026. The list includes AerynOS for its atomic updates, AnduinOS for its Windows-like familiarity, and Pop!_OS for its new COSMIC desktop environment. The author notes that the end of Windows 10 support is driving many new users to explore Linux.",
    Ratings: [{ userId: "u1", value: 5 },
  { userId: "u2", value: 2 },
  { userId: "u3", value: 4 },
  { userId: "u4", value: 1 }],
    Category: "Operating System",
    Views: 112},
  {Name: "Oxide Closes $200M Series C to Scale On-Premises Cloud Computing", 
    NewsArticle: "https://www.hpcwire.com/off-the-wire/oxide-closes-200m-series-c-to-scale-on-premises-cloud-computing/", 
    PublishDate: new Date(2026, 1, 9), 
    Description: "Oxide Computer Company announces a $200 million Series C funding round to scale its on-premises cloud computing platform. The company builds integrated rack-scale systems that provide hyperscale cloud capabilities—like API-driven self-service—directly in a company's own data center, offering an alternative to public cloud providers for enhanced security and control.",
    Ratings: [{ userId: "u1", value: 5 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 1 },
  { userId: "u4", value: 5 }],
    Category: "Cloud Computing",
    Views: 63},
  {Name: "TypeScript levels up with type stripping", 
    NewsArticle: "https://www.infoworld.com/article/2338883/typescript-levels-up-with-type-stripping.html", 
    PublishDate: new Date(2026, 0, 22), 
    Description: "This InfoWorld article discusses a new advancement in the TypeScript ecosystem: type stripping. By treating types as whitespace, modern JavaScript runtimes can run TypeScript code directly without a separate compilation step, which eliminates build delays and keeps stack traces accurate, paving the way for a faster, 'no-build' development workflow.",
    Ratings: [{ userId: "u1", value: 5 },
  { userId: "u2", value: 4 },
  { userId: "u3", value: 3 },
  { userId: "u4", value: 5 }],
    Category: "Programming",
    Views: 147}
]